# AEA: Reproducibility Checks in Codeocean

The workflow should be the same up until the verification stage, at which point you will use Codeocean to run the reproducibility check, as opposed to running directly in the statistical software. You can run Codeocean on your personal workspace or on CISER.

#### Create a Capsule
- In Codeocean, create a new capsule. Name the compute capsule as "(AEAREP-xxxx) Compute Capsule for: TITLE"
Example:
> AEAREP-1974 Compute Capsule for: Waiting to Choose: The Role of Deliberation in Intertemporal Choice

#### Environment
- Set up the environment specified by the authors. This includes software, version of that software, and any dependencies (packages). 
Example:
`Stata(16) with ssc packages estout and boottest`

#### Files and Directories
- Upload the code and data files to the `/code` and `/data` directories in Codeocean.

- There are only three directories in the Codeocean environment: `/data`; `/code`; `/results`.
    - All paths in the code must refer to one of these directories.
    - If the authors set their own globals, you change the globals to reflect these directories.
    - If the authors do not use globals, you should make the code more reproducible by setting globals in the `config.do` and amending the paths in the authors' code. 

- How you set up the Reproducible Run in Codeocean will, of course, depend upon the structure of the author's code.
    - If the authors use a `Master.do`, the "run" file in Codeocean should only need to include:
    ```
    #!/usr/bin/env bash
    set -ex

    # This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
    stata-mp -q do Master.do "$@"
    ``` 
    - If the authors provide instructions on a specific order in which to individually execute programs, each program will need to be added to the "run" file in that order. In this case, you should be including the `config.do` at the top of each program instead of only the `Master.do`. 

#### Log files

- As with any case, if the authors' code creates log files, you can comment out the log file creation in the `config.do`. 
- If the authors' code does not generate log files, you must amend the `config.do` to write the log files to the /results directory (i.e. ```global logdir "/results"```). 

#### Output

- Nothing is captured unless it is *explicitly* exported to the `/results` directory.
    - For example, you will not see any analysis files saved by the code unless they are saved as something such as `/results/cleaned_data.dta`. However, you do not *NEED* no do this. The program(s) should still run as long as the files are successfully created.

- Once you have finished editing and running the code in Codeocean, you should download the edited code and commit it to the repository. The best way to do this is similar to the steps taken during a revision. Delete, by hand (**NOT** git rm), the code files as you downloaded them onto your workspace. Then, place the amended codes into that same directory. Git add, commit, push. We should then be able to identify the changes you made to the code in order to run it on Codeocean. See further guidance [here](https://github.com/labordynamicsinstitute/replicability-training/blob/master/Updating_Materials.md).

- Download the `/results` directory and add it to the repository.

#### Jira

- The `Computing Environment` and `Working location of the data` should be "Codeocean"
- Share your CodeOcean capsule with `dataeditor@aeapubs.org`
- Add the CodeOcean shareable URL to the issue




